---
title: "[withmakers] TERA펀딩 데이터 분석"
output: flexdashboard::flex_dashboard
---

```{r setup, include=TRUE}
# save with encoding CP949

# library
library(flexdashboard)
library(data.table)
library(knitr)
library(kableExtra)
library(plotly)
library(dplyr)
library(ggmap)
library(ggplot2)
library(grid)
library(gridExtra)
library(Kormaps)
library(tmap)
library(leaflet)
library(RColorBrewer)

# RCOLORS
RCOLORS = brewer.pal(n = 8, name = 'Pastel2')

# set gmap api
register_google(key="AIzaSyCXh01QH5qS9MjT1thxp63fbVBtNlsebgc")

# check lat and long
seoul_lonlat = geocode('서울', source = 'google')

# read data
data = fread("c:/Users/user/Documents/TERA/output/data.csv")
```

Column {data-width=200}
-------------------------------------
   
### P2P부동산투자 예측 결과

```{r}
tmp = data.frame(
  투자상품 = c("제2460차 용인 보정동 하임아파트 담보상품","제2461차 여주시 현암동 단독주택 신축사업"),
  수익률 = c("9.5%","14%"),
  기간 = c("12개월","4개월"),
  등급 = c("A3","C1"),
  금액 = c("3억원","1억원"),
  연체확률 = c("0.01%","0.01%")
)
tmp %>% kable("html") %>% kable_styling(font_size = 15)
```   
 
### 투자기간

```{r}
ply = data %>% count(투자기간,TARGET) %>% plot_ly(x = ~투자기간, y = ~n, color= ~as.factor(TARGET), colors=RCOLORS, type="scatter") %>% layout(xaxis=list(fixedrange=TRUE)) %>% layout(yaxis=list(fixedrange=TRUE))
plotly::config(ply, displayModeBar = F)
```

### 수익률

```{r}
ply = data %>% count(수익률,TARGET) %>% plot_ly(x = ~수익률, y = ~n, color= ~as.factor(TARGET), colors=RCOLORS, type="scatter") %>% layout(xaxis=list(fixedrange=TRUE)) %>% layout(yaxis=list(fixedrange=TRUE))
plotly::config(ply, displayModeBar = F)
```

### 모집금액

```{r}
ply = data %>% count(모집금액,TARGET) %>% plot_ly(x = ~모집금액, y = ~n, color= ~as.factor(TARGET), colors=RCOLORS, type="scatter") %>% layout(xaxis=list(fixedrange=TRUE)) %>% layout(yaxis=list(fixedrange=TRUE))
plotly::config(ply, displayModeBar = F)
```

    
Column {data-width=200}
-------------------------------------
   
### 등급

```{r}
ply = data %>% count(등급,TARGET) %>% plot_ly(x = ~등급, y = ~n, color= ~as.factor(TARGET), colors=RCOLORS, type="bar") %>% layout(xaxis=list(fixedrange=TRUE)) %>% layout(yaxis=list(fixedrange=TRUE))
plotly::config(ply, displayModeBar = F)
```

### 건물
    
```{r}
ply = data %>% count(건물,TARGET) %>% plot_ly(x = ~건물, y = ~n, color= ~as.factor(TARGET), colors=RCOLORS, type="bar") %>% layout(xaxis=list(fixedrange=TRUE)) %>% layout(yaxis=list(fixedrange=TRUE))
plotly::config(ply, displayModeBar = F)
```

### 투자유형
    
```{r}
ply = data %>% count(투자유형,TARGET) %>% plot_ly(x = ~투자유형, y = ~n, color= ~as.factor(TARGET), colors=RCOLORS, type="bar") %>% layout(xaxis=list(fixedrange=TRUE)) %>% layout(yaxis=list(fixedrange=TRUE))
plotly::config(ply, displayModeBar = F)
```

### 투자인원
    
```{r}
ply = data %>% count(투자인원,TARGET) %>% plot_ly(x = ~투자인원, y = ~n, color= ~as.factor(TARGET), colors=RCOLORS, type="scatter") %>% layout(xaxis=list(fixedrange=TRUE)) %>% layout(yaxis=list(fixedrange=TRUE))
plotly::config(ply, displayModeBar = F)
```

Column {data-width=200}
-------------------------------------
   
### 연체 지역

```{r}
tmp = data[TARGET=="연체",]
ply = tmp %>% count(지역,TARGET) %>% plot_ly(x = ~지역, y = ~n, type="bar",marker = list(color ="rgb(204,204,204)")) %>% layout(xaxis=list(fixedrange=TRUE)) %>% layout(yaxis=list(fixedrange=TRUE))
plotly::config(ply, displayModeBar = F)
```   
 
### 도시유형
    
```{r}
ply = data %>% count(도시유형,TARGET) %>% plot_ly(x = ~도시유형, y = ~n, color= ~as.factor(TARGET), colors=RCOLORS, type="bar") %>% layout(xaxis=list(fixedrange=TRUE)) %>% layout(yaxis=list(fixedrange=TRUE))
plotly::config(ply, displayModeBar = F)
```

### 역세권
    
```{r}
ply = data %>% count(역세권,TARGET) %>% plot_ly(x = ~역세권, y = ~n, color= ~as.factor(TARGET), colors=RCOLORS, type="bar") %>% layout(xaxis=list(fixedrange=TRUE)) %>% layout(yaxis=list(fixedrange=TRUE))
plotly::config(ply, displayModeBar = F)
```

### 주택
    
```{r}
ply = data %>% count(주택,TARGET) %>% plot_ly(x = ~주택, y = ~n, color= ~as.factor(TARGET), colors=RCOLORS, type="bar") %>% layout(xaxis=list(fixedrange=TRUE)) %>% layout(yaxis=list(fixedrange=TRUE))
plotly::config(ply, displayModeBar = F)
```

Column {data-width=400}
-------------------------------------
   
### 지도

```{r}
# Make data with several positions
data_red = data[TARGET=="연체",list(지역,lon,lat)]
data_red = data_red[,.N,by=list(지역,lon,lat)]
data_red[,N:=log(N^2)]
data_blue = data[TARGET!="연체",list(지역,lon,lat)]
data_blue = data_blue[,.N,by=list(지역,lon,lat)]
data_blue[,N:=log(N^2)]

# Initialize the leaflet map:
leaflet() %>% 
  setView(lng=seoul_lonlat[1],lat=seoul_lonlat[2],zoom=6) %>%
  
  # Add two tiles
  addProviderTiles("Esri.WorldImagery", group="인공위성") %>%
  addTiles(options = providerTileOptions(noWrap = TRUE), group="일반지도") %>%
  
  # Add 2 marker groups
  addCircleMarkers(data=data_blue, lng=~lon , lat=~lat, radius=~N, color="black",  fillColor="dodgerblue", stroke = TRUE, fillOpacity = 0.8, group="상환완료") %>%
  addCircleMarkers(data=data_red, lng=~lon , lat=~lat, radius=~N, color="black",  fillColor="red", stroke = TRUE, fillOpacity = 0.8, group="연체") %>%
  
  # Add the control widget
  addLayersControl(overlayGroups = c("연체","상환완료") , baseGroups = c("인공위성","일반지도"), options = layersControlOptions(collapsed = FALSE))
```   
 
